import json

# All products scraped from the BestBottles accessories page
# https://www.bestbottles.com/all-bottles/accessories/velvet-bags-organza-gusseted-bags-gift-box-purchase.php
scraped = [
    # === FUNNELS ===
    {"websiteSku": "FunnelMetalGl", "itemName": "Small Gold Metal Funnel", "category": "Accessory", "family": "Funnel", "webPrice1pc": 0.44, "webPrice10pc": 0.42, "productUrl": "https://www.bestbottles.com/product/Funnel-small-metal-Gold-color", "image": "https://www.bestbottles.com/images/store/FunnelMetalGl.png", "stockStatus": "In Stock"},
    {"websiteSku": "FunnelMetalSl", "itemName": "Small Silver Metal Funnel", "category": "Accessory", "family": "Funnel", "webPrice1pc": 0.44, "webPrice10pc": 0.42, "productUrl": "https://www.bestbottles.com/product/Funnel-Small-Metal-Silver", "image": "https://www.bestbottles.com/images/store/FunnelMetalSl.png", "stockStatus": "In Stock"},
    {"websiteSku": "Plastic Funnels", "itemName": "Small Plastic Funnel", "category": "Accessory", "family": "Funnel", "webPrice1pc": 0.33, "webPrice10pc": 0.31, "productUrl": "https://www.bestbottles.com/product/Funnel-Plastic-small", "image": "https://www.bestbottles.com/images/store/Plastic Funnels.png", "stockStatus": "In Stock"},
    # === DROPPERS ===
    {"websiteSku": "Drp18-40015mlBlckBulb", "itemName": "Black Rubber Bulb Dropper Black Cap 15ml 18-400", "category": "Accessory", "family": "Dropper", "webPrice1pc": 0.45, "webPrice10pc": None, "productUrl": "https://www.bestbottles.com/product/Dropper-black-rubber-bulb-black-trim-glass-Pipette-15ml", "image": "https://www.bestbottles.com/images/store/Drp18-40015mlBlckBulb.png", "stockStatus": "In Stock"},
    {"websiteSku": "Drp20-4001ozBlckBulb", "itemName": "Black Rubber Bulb Dropper Black Cap 1oz 20-400", "category": "Accessory", "family": "Dropper", "webPrice1pc": 0.45, "webPrice10pc": None, "productUrl": "https://www.bestbottles.com/product/Dropper-glass-Black-Rubber-Bulb-black-trim-7x76", "image": "https://www.bestbottles.com/images/store/Drp20-4001ozBlckBulb.png", "stockStatus": "In Stock"},
    {"websiteSku": "Drp20-4002ozBlckBulb", "itemName": "Black Rubber Bulb Dropper Black Cap 2oz 20-400", "category": "Accessory", "family": "Dropper", "webPrice1pc": 0.50, "webPrice10pc": None, "productUrl": "https://www.bestbottles.com/product/Dropper-glass-Black-Rubber-Bulb-black-trim7x89", "image": "https://www.bestbottles.com/images/store/Drp20-4002ozBlckBulb.png", "stockStatus": "In Stock"},
    {"websiteSku": "Drp18-415Cu", "itemName": "White Rubber Bulb Dropper Copper Cap 18-415", "category": "Accessory", "family": "Dropper", "webPrice1pc": 0.55, "webPrice10pc": None, "productUrl": "https://www.bestbottles.com/product/Dropper-white-rubber-bulb-copper-trim-glass-Pipette", "image": "https://www.bestbottles.com/images/store/Drp18-415Cu.png", "stockStatus": "In Stock"},
    # === ORGANZA BAGS ===
    {"websiteSku": "OBagBlack4x6", "itemName": "Black Organza Sheer Gusseted Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Bag-pouch-Black--4x6", "image": "https://www.bestbottles.com/images/store/OBagBlack4x6.png", "stockStatus": "Out Of Stock"},
    {"websiteSku": "OBagBlack5x8", "itemName": "Black Organza Sheer Gusseted Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Black-5x8", "image": "https://www.bestbottles.com/images/store/OBagBlack5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagChGreen4x6", "itemName": "Christmas Green Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Green-4x6", "image": "https://www.bestbottles.com/images/store/OBagChGreen5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagChGreen5x8", "itemName": "Christmas Green Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Green-5x8", "image": "https://www.bestbottles.com/images/store/OBagChGreen5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagGold4x6", "itemName": "Gold Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Gold-4x6", "image": "https://www.bestbottles.com/images/store/OBagGold4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagGold5x8", "itemName": "Gold Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Gold-5x8", "image": "https://www.bestbottles.com/images/store/OBagGold5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagGreen4x6", "itemName": "Green Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Green-4x6", "image": "https://www.bestbottles.com/images/store/OBagGreen4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagGreen5x8", "itemName": "Green Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Green-5x8", "image": "https://www.bestbottles.com/images/store/OBagGreen5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagIvory4x6", "itemName": "Ivory Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Ivory-4x6", "image": "https://www.bestbottles.com/images/store/OBagIvory4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagIvory5x8", "itemName": "Ivory Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Ivory-5x8", "image": "https://www.bestbottles.com/images/store/OBagIvory4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagLavender4x6", "itemName": "Lavender Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Lavender-4x6", "image": "https://www.bestbottles.com/images/store/OBagLavender5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagLavender5x8", "itemName": "Lavender Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Lavender-5x8", "image": "https://www.bestbottles.com/images/store/OBagLavender5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagLightPurple5x8", "itemName": "Light Purple Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Light-Purple-5x8", "image": "https://www.bestbottles.com/images/store/OBagLightPurple5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagPink4x6", "itemName": "Pink Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pink-4x6", "image": "https://www.bestbottles.com/images/store/OBagPink4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagPink5x8", "itemName": "Pink Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pink-5x8", "image": "https://www.bestbottles.com/images/store/OBagPink4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagPurple4x6", "itemName": "Purple Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Purple-4x6", "image": "https://www.bestbottles.com/images/store/OBagPurple4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagPurple5x8", "itemName": "Purple Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Purple-5x8", "image": "https://www.bestbottles.com/images/store/OBagPurple4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagRed4x6", "itemName": "Red Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Red-4x6", "image": "https://www.bestbottles.com/images/store/OBagRed4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagRed5x8", "itemName": "Red Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Pouch-Red-5x8", "image": "https://www.bestbottles.com/images/store/OBagRed5x8.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagSilver4x6", "itemName": "Silver Gray Organza Sheer Gift Bag 4x6", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.77, "webPrice10pc": 0.73, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Silver-4x6", "image": "https://www.bestbottles.com/images/store/OBagSilver4x6.png", "stockStatus": "In Stock"},
    {"websiteSku": "OBagSilver5x8", "itemName": "Silver Gray Organza Sheer Gift Bag 5x8", "category": "Packaging", "family": "Organza Bag", "webPrice1pc": 0.88, "webPrice10pc": 0.84, "productUrl": "https://www.bestbottles.com/product/Organza-Sheer-Gift-Bag-Silver-5x8", "image": "https://www.bestbottles.com/images/store/OBagSilver4x6.png", "stockStatus": "In Stock"},
    # === VELVETEEN BAGS ===
    {"websiteSku": "VBagBlack4x3", "itemName": "Black Velveteen Gift Bag 4x3", "category": "Packaging", "family": "Velveteen Bag", "webPrice1pc": 0.44, "webPrice10pc": 0.42, "productUrl": "https://www.bestbottles.com/product/Velveteen-gift-bag-Red-4x3", "image": "https://www.bestbottles.com/images/store/VBagBlack4x3.png", "stockStatus": "In Stock"},
    {"websiteSku": "VBagBlack4x5", "itemName": "Black Velveteen Gift Bag 5.5x4", "category": "Packaging", "family": "Velveteen Bag", "webPrice1pc": 0.55, "webPrice10pc": 0.52, "productUrl": "https://www.bestbottles.com/product/Small-velveteen-Black-gift-bag-pouch-4x5", "image": "https://www.bestbottles.com/images/store/VBagBlack4x5.png", "stockStatus": "Out Of Stock"},
    {"websiteSku": "VBagBlue4x3", "itemName": "Blue Velveteen Gift Bag 4x3", "category": "Packaging", "family": "Velveteen Bag", "webPrice1pc": 0.44, "webPrice10pc": 0.42, "productUrl": "https://www.bestbottles.com/product/Velveteen-gift-bag-pouch-Blue-4x3", "image": "https://www.bestbottles.com/images/store/VBagBlue4x3.png", "stockStatus": "In Stock"},
    {"websiteSku": "VBagBlue4x5", "itemName": "Blue Velveteen Gift Bag 5.5x4", "category": "Packaging", "family": "Velveteen Bag", "webPrice1pc": 0.55, "webPrice10pc": 0.52, "productUrl": "https://www.bestbottles.com/product/Small-velveteen-Black-gift-bag-pouch-4x5", "image": "https://www.bestbottles.com/images/store/VBagBlue4x5.png", "stockStatus": "In Stock"},
    {"websiteSku": "VBagGreen4x3", "itemName": "Green Velveteen Gift Bag 4x3", "category": "Packaging", "family": "Velveteen Bag", "webPrice1pc": 0.44, "webPrice10pc": 0.42, "productUrl": "https://www.bestbottles.com/product/Velveteen-gift-bag-pouch-Green-4x3", "image": "https://www.bestbottles.com/images/store/VBagGreen4x3.png", "stockStatus": "In Stock"},
    {"websiteSku": "VBagGreen4x5", "itemName": "Green Velveteen Gift Bag 5.5x4", "category": "Packaging", "family": "Velveteen Bag", "webPrice1pc": 0.55, "webPrice10pc": 0.52, "productUrl": "https://www.bestbottles.com/product/Small-velveteen-Green-bag-pouch-4x5", "image": "https://www.bestbottles.com/images/store/VBagGreen4x5.png", "stockStatus": "In Stock"},
    {"websiteSku": "VBagRed4x3", "itemName": "Red Velveteen Gift Bag 4x3", "category": "Packaging", "family": "Velveteen Bag", "webPrice1pc": 0.44, "webPrice10pc": 0.42, "productUrl": "https://www.bestbottles.com/product/Velveteen-gift-bag-pouch-Red-4x3", "image": "https://www.bestbottles.com/images/store/VBagRed4x3.png", "stockStatus": "In Stock"},
    {"websiteSku": "VBagRed4x5", "itemName": "Red Velveteen Gift Bag 5.5x4", "category": "Packaging", "family": "Velveteen Bag", "webPrice1pc": 0.55, "webPrice10pc": 0.52, "productUrl": "https://www.bestbottles.com/product/Small-velveteen-Red-gift-bag-pouch-4x5", "image": "https://www.bestbottles.com/images/store/VBagRed4x5.png", "stockStatus": "In Stock"},
    # === GIFT BOXES (window/folding) ===
    {"websiteSku": "BoxBWndwBlueFthr", "itemName": "Blue Feather Window Gift Box 1.5x1.5x3.5", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-B-small-window-Blue-feather", "image": "https://www.bestbottles.com/images/store/BoxBWndwBlueFthr.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxBWndwEarthBrush", "itemName": "Earth Brush Window Gift Box 1.5x1.5x3.5", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-B-small-window-earth-brush", "image": "https://www.bestbottles.com/images/store/BoxBWndwEarthBrush.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxBWndwGreenBrush", "itemName": "Green Brush Window Gift Box 1.5x1.5x3.5", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-B-small-window-Green-brush", "image": "https://www.bestbottles.com/images/store/BoxBWndwGreenBrush.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxBWndwOrngShade", "itemName": "Orange Shade Window Gift Box 1.5x1.5x3.5", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-B-small-window-Orange-Shade", "image": "https://www.bestbottles.com/images/store/BoxBWndwOrngShade.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxBWndwSlvrChks", "itemName": "Silver Checks Window Gift Box 1.5x1.5x3.5", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-B-small-window-green-shade", "image": "https://www.bestbottles.com/images/store/BoxBWndwSlvrChks.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxCWndwBlueDots", "itemName": "Blue Dots Window Gift Box Small", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-C-small-window-Blue-dots", "image": "https://www.bestbottles.com/images/store/BoxCWndwBlueDots.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxCWndwGreenPrint", "itemName": "Green Print Window Gift Box Small", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-C-small-window-Green-print", "image": "https://www.bestbottles.com/images/store/BoxCWndwGreenPrint.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxCWndwGrnShd", "itemName": "Green Shade Window Gift Box Small", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-C-small-window-Green-Shade", "image": "https://www.bestbottles.com/images/store/BoxCWndwGrnShd.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxCWndwSlvrSunFlwr", "itemName": "Silver Sunflower Window Gift Box Small", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-C-small-window-Silver-Sunflower", "image": "https://www.bestbottles.com/images/store/BoxCWndwSlvrSunFlwr.png", "stockStatus": "In Stock"},
    {"websiteSku": "BoxCWndwWhite", "itemName": "Plain White Window Gift Box Small", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.35, "webPrice10pc": 0.33, "productUrl": "https://www.bestbottles.com/product/Gift-box-C-small-window-white-color", "image": "https://www.bestbottles.com/images/store/BoxCWndwWhite.png", "stockStatus": "Out Of Stock"},
    {"websiteSku": "BoxECreamMatteCube", "itemName": "Cream Matte Cube Gift Box 4x3.5x4", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.75, "webPrice10pc": 0.71, "productUrl": "https://www.bestbottles.com/product/Gift-Box-Cream-butter-balm-color-4x3-5x4", "image": "https://www.bestbottles.com/images/store/BoxECreamMatteCube.png", "stockStatus": "Out Of Stock"},
    {"websiteSku": "BoxECreamMatteRctMed", "itemName": "Cream Matte Rectangle Gift Box 3.1x2.75x5.9", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.75, "webPrice10pc": 0.71, "productUrl": "https://www.bestbottles.com/product/Gift-Box-Cream-butter-balm-color-3-1x2-75x5-9", "image": "https://www.bestbottles.com/images/store/BoxECreamMatteRctMed.png", "stockStatus": "Out Of Stock"},
    {"websiteSku": "BoxWhite101020", "itemName": "White Folding Gift Box 1x1x2", "category": "Packaging Box", "family": "Gift Box", "webPrice1pc": 0.25, "webPrice10pc": 0.24, "productUrl": "https://www.bestbottles.com/product/Gift-Box-White-1x1x2", "image": "https://www.bestbottles.com/images/store/BoxWhite101020.png", "stockStatus": "Out Of Stock"},
    # === SHIPPING BOXES ===
    {"websiteSku": "Box-4x4x4", "itemName": "Brown Corrugated Shipping Box 4x4x4", "category": "Packaging Box", "family": "Shipping Box", "webPrice1pc": 0.45, "webPrice10pc": 0.43, "productUrl": "https://www.bestbottles.com/product/Brown-Shipping-Packaging-Box-4x4x4", "image": "https://www.bestbottles.com/images/store/Box-4x4x4.png", "stockStatus": "In Stock"},
    {"websiteSku": "Box-5x5x5", "itemName": "Brown Corrugated Shipping Box 5x5x5", "category": "Packaging Box", "family": "Shipping Box", "webPrice1pc": 0.52, "webPrice10pc": 0.49, "productUrl": "https://www.bestbottles.com/product/Brown-Shipping-Packaging-Box-5x5x5", "image": "https://www.bestbottles.com/images/store/Box-5x5x5.png", "stockStatus": "In Stock"},
    # === RECLOSABLE PLASTIC BAGS ===
    {"websiteSku": "RecloseableBags12x15", "itemName": "Reclosable Plastic Bags 12x15 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 25.00, "webPrice10pc": 23.75, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-12x15", "image": "https://www.bestbottles.com/images/store/RecloseableBags12x15.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags2x10", "itemName": "Reclosable Plastic Bags 2x10 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 2.40, "webPrice10pc": 2.28, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-Incense-2x10", "image": "https://www.bestbottles.com/images/store/RecloseableBags2x10.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags2x12", "itemName": "Reclosable Plastic Bags 2x12 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 2.60, "webPrice10pc": 2.47, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-Incense-2x12", "image": "https://www.bestbottles.com/images/store/RecloseableBags2x12.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags3x12", "itemName": "Reclosable Plastic Bags 3x12 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 3.00, "webPrice10pc": 2.85, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-Incense-3x12", "image": "https://www.bestbottles.com/images/store/RecloseableBags3x12.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags3x3", "itemName": "Reclosable Plastic Bags 3x3 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 1.50, "webPrice10pc": 1.43, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-3x3", "image": "https://www.bestbottles.com/images/store/RecloseableBags3x3.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags3x4", "itemName": "Reclosable Plastic Bags 3x4 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 1.50, "webPrice10pc": 1.43, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-Bag-Clear-3x4", "image": "https://www.bestbottles.com/images/store/RecloseableBags3x4.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags4x12", "itemName": "Reclosable Plastic Bags 4x12 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 3.50, "webPrice10pc": 3.33, "productUrl": "https://www.bestbottles.com/product/Plastic-reclosable-Bag-Clear-4x12", "image": "https://www.bestbottles.com/images/store/RecloseableBags4x12.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags4X5", "itemName": "Reclosable Plastic Bags 4x5 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 2.00, "webPrice10pc": 1.90, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-4x5", "image": "https://www.bestbottles.com/images/store/RecloseableBags4X5.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags4X6", "itemName": "Reclosable Plastic Bags 4x6 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 2.25, "webPrice10pc": 2.14, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-4x6", "image": "https://www.bestbottles.com/images/store/RecloseableBags4X6.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags4X8", "itemName": "Reclosable Plastic Bags 4x8 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 2.60, "webPrice10pc": 2.47, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-4x8", "image": "https://www.bestbottles.com/images/store/RecloseableBags4X8.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags6x10", "itemName": "Reclosable Plastic Bags 6x10 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 4.00, "webPrice10pc": 3.80, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-6x10", "image": "https://www.bestbottles.com/images/store/RecloseableBags6x10.png", "stockStatus": "In Stock"},
    {"websiteSku": "RecloseableBags9x12", "itemName": "Reclosable Plastic Bags 9x12 (100 pk)", "category": "Packaging", "family": "Plastic Bag", "webPrice1pc": 7.50, "webPrice10pc": 7.13, "productUrl": "https://www.bestbottles.com/product/Plastic-Reclosable-bag-Clear-8x12", "image": "https://www.bestbottles.com/images/store/RecloseableBags9x12.png", "stockStatus": "In Stock"},
]

# Load existing data
with open("data/grace_products_clean.json") as f:
    existing = json.load(f)

existing_skus = {(item.get("websiteSku") or "").lower().strip() for item in existing}

print(f"Total scraped from accessories page: {len(scraped)}")
print(f"Existing items in grace_products_clean: {len(existing)}")
print()

new_items = []
already_present = []

for item in scraped:
    sku_key = (item["websiteSku"] or "").lower().strip()
    if sku_key in existing_skus:
        already_present.append(item["websiteSku"])
    else:
        new_items.append(item)

print(f"Already in grace_products_clean: {len(already_present)}")
if already_present:
    print("  ->", already_present)

print(f"\nNEW items to add: {len(new_items)}")
print()

# Breakdown by family
from collections import Counter
family_counts = Counter(i["family"] for i in new_items)
print("Breakdown by product family:")
for fam, count in sorted(family_counts.items()):
    print(f"  {fam}: {count}")

print()
print("Items with 10pc pricing:", sum(1 for i in new_items if i.get("webPrice10pc")))
print("Items WITHOUT 10pc pricing (droppers only):", sum(1 for i in new_items if not i.get("webPrice10pc")))

# Merge into existing and save
merged = existing + new_items
with open("data/grace_products_clean.json", "w") as f:
    json.dump(merged, f, indent=2)

print(f"\n✅ Saved {len(merged)} total items to data/grace_products_clean.json")
print(f"   ({len(new_items)} new items added)")
